### ISSUE TITLE
MkComponent is not defined

### ISSUE THREAD

**Issue by dandevmsc** [yellowbean/AbsBox#3]
Hi Xiaoyu 
I was trying to test the test01 run from the doc example.

def read_pricing(self, pricing):
        if pricing:
            return mkComponent(pricing)
        return None

mkComponent is not defined in the component.py file

**Comment by yellowbean** [comment]
Thanks, I'm looking into it

**Comment by yellowbean** [comment]
Hi, @dandevmsc 

Thanks for your patience.

the issue was fixed at version 0.9.3. and I've update the deal sample in the doc website.
see full test code below in html
[0.92.html.zip](https://github.com/yellowbean/AbsBox/files/11009024/0.92.html.zip)

There isn't much sample in English doc site yet, but I'm happy to add deal samples if there are deal documents available for me.

Cheers

**Comment by dandevmsc** [comment]
Okay perfect thanks! 
This is a great package and I will keep on testing out features.
I will work on modelling triggers now and can look to provide you some deal docs to have some examples.
